# Generated by Django 3.2.9 on 2021-11-19 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('school', models.CharField(blank=True, max_length=150)),
                ('student_number', models.CharField(blank=True, max_length=150)),
                ('major', models.CharField(blank=True, max_length=150)),
                ('login_as', models.BooleanField(default=False)),
                ('temperature', models.IntegerField(default=36)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
